#!/usr/bin/env bash
# Rebuild memories/index.md from all memory files.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MEMORIES_DIR="$REPO_ROOT/memories"
INDEX="$MEMORIES_DIR/index.md"

{
  echo "# Memory Index"
  echo ""
  echo "Auto-generated by \`scripts/reindex.sh\`. Do not edit manually."
  echo ""
  echo "| Date | File | Tags | Summary |"
  echo "|------|------|------|---------|"

  count=0
  for f in "$MEMORIES_DIR"/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-*.md; do
    [[ -f "$f" ]] || continue
    filename="$(basename "$f")"

    date_val=$(grep '^date:' "$f" | head -1 | sed 's/date: *//')
    tags_val=$(grep '^tags:' "$f" | head -1 | sed 's/tags: *//')
    summary_val=$(grep '^summary:' "$f" | head -1 | sed 's/summary: *//')

    echo "| $date_val | [$filename]($filename) | $tags_val | $summary_val |"
    count=$((count + 1))
  done

  if [[ $count -eq 0 ]]; then
    echo ""
    echo "_No memories yet. Use \`bash scripts/add-memory.sh\` to add your first memory._"
  fi
} > "$INDEX"

echo "Index rebuilt: $count memories."
